addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.3")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.25")
addSbtPlugin("com.lihaoyi" % "workbench" % "0.4.1")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")